/// Compact summary of the controller's mode + pending state, in the
/// shape the status bar renders. Generated by the controller and
/// consumed read-only by the SwiftUI status view; using a dedicated
/// struct decouples the status surface from the controller's pendingKeys
/// / pendingCount internals.
///
/// `detailText` is `nil` when there's nothing pending (no count, no
/// partial chord). Non-nil examples: `"3"` after typing a count digit,
/// `"<Space>"` after pressing the leader, `"3 g"` after a count + first
/// key of a multi-key motion.
public struct VimStatusPresentation: Sendable, Equatable {
    public let mode: VimMode
    public let detailText: String?

    public init(mode: VimMode, detailText: String? = nil) {
        self.mode = mode
        self.detailText = detailText
    }

    /// Builds a presentation from the controller's authoritative state.
    /// Pulled out as a static helper so tests can verify the formatter
    /// independently of the controller's other state-machine work.
    public static func make(
        mode: VimMode,
        pendingKeys: [VimKey],
        pendingCount: Int?,
        pendingCharArgument: PendingCharArgument? = nil,
        pendingOperator: PendingOperator? = nil
    ) -> VimStatusPresentation {
        var parts: [String] = []
        if let pendingOperator {
            // `3 d`, `3 d 2`, `d`. Pre-count of 1 is implicit and
            // suppressed so a bare `d` doesn't display as `"1 d"`.
            if pendingOperator.preCount > 1 {
                parts.append("\(pendingOperator.preCount)")
            }
            parts.append(pendingOperator.kind.statusLabel)
            if let count = pendingCount { parts.append("\(count)") }
        } else {
            if let count = pendingCount { parts.append("\(count)") }
        }
        parts.append(contentsOf: pendingKeys.map(\.displayString))
        if let pendingCharArgument {
            parts.append("\(pendingCharArgument.statusLabel) <a-z>")
        }
        let detail = parts.isEmpty ? nil : parts.joined(separator: " ")
        return VimStatusPresentation(mode: mode, detailText: detail)
    }
}
